export enum PayrollCycle {
  MONTHLY = 'MONTHLY',
  SEMI_MONTHLY = 'SEMI_MONTHLY',
}

export enum ProrateSalaryFormula {
  '26_DAYS' = '26_DAYS',
  AVERAGE_WORKING_DAYS = 'AVERAGE_WORKING_DAYS',
  WORKING_DAYS = 'WORKING_DAYS',
  CALENDAR_DAYS = 'CALENDAR_DAYS',
}

export enum CompanyPomSgCpfSubmissionPlatform {
  CPF_EZPAY = 'CPF_EZPAY',
  CRIMSON_LOGIC = 'CRIMSON_LOGIC',
}

export enum CompanyPomSgCpfPaymentMode {
  DIRECT_DEBIT_COMPANY = 'DIRECT_DEBIT_COMPANY',
  DIRECT_DEBIT_VENDOR = 'DIRECT_DEBIT_VENDOR',
}

export enum CompanyPomSgESubmissionServices {
  CPF_SERVICES = 'CPF_SERVICES',
  CPF_EZPAY = 'CPF_EZPAY',
  EMPLOYMENT_INCOME_RECORDS = 'EMPLOYMENT_INCOME_RECORDS',
  TAX_CLEARANCE = 'TAX_CLEARANCE',
  GPL_PORTAL = 'GPL_PORTAL',
  MINDEF_PORTAL = 'MINDEF_PORTAL',
}

export enum CompanyPomHkMpfProvider {
  NONE = 'NONE',
  AIA_COMPANY_TRUSTEE_LIMITED = 'AIA_COMPANY_TRUSTEE_LIMITED',
  HSBC_PROVIDENT_FUND_TRUSTEE_LIMITED = 'HSBC_PROVIDENT_FUND_TRUSTEE_LIMITED',
  MANULIFE_PROVIDENT_FUNDS_TRUST_COMPANY_LIMITED = 'MANULIFE_PROVIDENT_FUNDS_TRUST_COMPANY_LIMITED',
  HSBC_PROVIDENT_FUND_TRUSTEE = 'HSBC_PROVIDENT_FUND_TRUSTEE',
}

export enum CompanyPomVnShuiProvider {
  TS24 = 'TS24',
  EBH = 'EBH',
  BKAV = 'BKAV',
  DICHVUCONG = 'DICHVUCONG',
  VNPT = 'VNPT',
  VIETTEL = 'VIETTEL',
}

export enum CompannyPomIdContributionForBpjsOnSalary {
  ACTUAL_SALARY = 'ACTUAL_SALARY',
}

export enum CompanyPomPhStatutoryDeductions {
  MIDDLE_OF_THE_MONTH = 'MIDDLE_OF_THE_MONTH',
  END_OF_THE_MONTH = 'END_OF_THE_MONTH',
}
