export enum DataGridExportContext {
  STAFF_AUDIT_CLIENT_LIST = 'STAFF_AUDIT_CLIENT_LIST',
  STAFF_AUDIT_CLIENT_HIRES = 'STAFF_AUDIT_CLIENT_HIRES',
  STAFF_AUDIT_CLIENT_SERVICE_AGREEMENTS = 'STAFF_AUDIT_CLIENT_SERVICE_AGREEMENTS',
  COMPANY_PEOPLE_ONBOARDING = 'COMPANY_PEOPLE_ONBOARDING',
  COMPANY_PEOPLE_WORKFORCE = 'COMPANY_PEOPLE_WORKFORCE',
}
