name: PR Size Labeller

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  main:
    runs-on: tableau-server
    steps:
      - name: Label the PR
        uses: pascalgn/size-label-action@v0.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORED: "*.md\n*lock\n**/?(*.)+(cy).[jt]s?(x)?(.snap)\n**/?(*.)+(spec|test).[jt]s?(x)?(.snap)\n.github/**\napps/mocks*/**"
