name: Slash Command

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  main:
    runs-on: tableau-server
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          permission: none
          issue-type: pull-request
          commands: |
            run-ci
            run-stats
            run-ci-cypress
